FROM ubuntu
LABEL maintainer="JGJones"

# Reference:
# https://github.com/byt3bl33d3r/CrackMapExec/wiki/Installation

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
	apt-get install -y \
	libssl-dev \
	libffi-dev \
	python-dev \
	python-pip \
	build-essential \
	tmux \
	git

USER root

WORKDIR /opt
RUN /bin/bash -l -c "git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec"
WORKDIR CrackMapExec
RUN rm -rf .git && \
	/bin/bash -l -c "pip install -r requirements.txt" && \
	/bin/bash -l -c "python setup.py install" && \
	/bin/bash -l -c "cme -h"


# Copy tmux.conf
COPY tmux.conf /root/.tmux.conf

VOLUME /tmp/data

WORKDIR /tmp/data

# Clean up

RUN apt-get --purge remove ca-certificates build-essential python-pip git -y && \
	apt-get --purge autoremove -y && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["tmux"]