FROM ubuntu
LABEL maintainer - JGJ

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y enum4linux && \
	rm -rf /var/lib/apt/lists/*

USER root

ENTRYPOINT [ "enum4linux" ]
CMD [ "-h" ]